name: Run tests and upload coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 2
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests with coverage
        run: pnpm test --coverage
      
      - name: List coverage files
        run: ls -R ./coverage || echo "No coverage files found"


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: interactive-video-labs/interactive-video-core
          files: ./coverage/lcov.info

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: interactive-video-labs/interactive-video-core
          files: ./test-report.junit.xml
